CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(512),
  role VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_users_public_id UNIQUE (public_id),
  CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE email_verification_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_email_verification_tokens_public_id UNIQUE (public_id),
  CONSTRAINT uk_email_verification_tokens_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_email_verification_tokens_user
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_email_verification_tokens_user_id
  ON email_verification_tokens (user_id);

CREATE INDEX idx_email_verification_tokens_expires_at
  ON email_verification_tokens (expires_at);

CREATE TABLE password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_password_reset_tokens_public_id UNIQUE (public_id),
  CONSTRAINT uk_password_reset_tokens_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_password_reset_tokens_user
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_password_reset_tokens_user_id
  ON password_reset_tokens (user_id);

CREATE INDEX idx_password_reset_tokens_expires_at
  ON password_reset_tokens (expires_at);

CREATE TABLE projects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID          NOT NULL,
  name        VARCHAR(255)  NOT NULL,
  description TEXT,
  created_by  BIGINT        NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at  TIMESTAMP WITH TIME ZONE,

  CONSTRAINT uk_projects_public_id UNIQUE (public_id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_projects_created_by ON projects (created_by);
CREATE INDEX idx_projects_deleted_at ON projects (deleted_at);
