CREATE TABLE projects (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID          NOT NULL,
  name        VARCHAR(255)  NOT NULL,
  description TEXT,
  created_by  BIGINT        NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at  TIMESTAMP WITH TIME ZONE,

  CONSTRAINT uk_projects_public_id UNIQUE (public_id),
  CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_projects_created_by ON projects (created_by);
CREATE INDEX idx_projects_deleted_at ON projects (deleted_at);
