-- =============================================================
-- Target Config
-- =============================================================
CREATE TABLE target_configs (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                UUID          NOT NULL,
  project_id               BIGINT        NOT NULL,
  version                  INT           NOT NULL DEFAULT 1,
  name                     VARCHAR(255),
  method                   VARCHAR(10)   NOT NULL,
  url                      TEXT          NOT NULL,
  headers                  JSONB,
  query_params             JSONB,
  body_template            TEXT,
  response_path            VARCHAR(500),
  timeout_ms               INT           NOT NULL DEFAULT 30000,
  request_field_snapshot   JSONB,
  response_field_snapshot  JSONB,
  raw_curl                 TEXT,
  last_test_status         VARCHAR(30),
  last_tested_at           TIMESTAMP WITH TIME ZONE,
  created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_target_configs_public_id UNIQUE (public_id),
  CONSTRAINT uk_target_configs_project   UNIQUE (project_id),
  CONSTRAINT fk_target_configs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_target_configs_project ON target_configs (project_id);

-- =============================================================
-- Secret Refs
-- =============================================================
CREATE TABLE secret_refs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        UUID          NOT NULL,
  project_id       BIGINT        NOT NULL,
  owner_type       VARCHAR(50)   NOT NULL,
  owner_id         BIGINT        NOT NULL,
  secret_name      VARCHAR(255)  NOT NULL,
  secret_location  VARCHAR(50)   NOT NULL,
  secret_path      VARCHAR(500),
  encrypted_value  TEXT          NOT NULL,
  masked_value     VARCHAR(255)  NOT NULL,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_secret_refs_public_id UNIQUE (public_id),
  CONSTRAINT fk_secret_refs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_secret_refs_owner ON secret_refs (owner_type, owner_id);

-- =============================================================
-- AI Config
-- =============================================================
CREATE TABLE ai_configs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id          UUID          NOT NULL,
  project_id         BIGINT        NOT NULL,
  version            INT           NOT NULL DEFAULT 1,
  key_source         VARCHAR(20)   NOT NULL DEFAULT 'PLATFORM',
  provider           VARCHAR(50)   NOT NULL,
  base_url           VARCHAR(500),
  evaluation_model   VARCHAR(255)  NOT NULL,
  generation_model   VARCHAR(255),
  temperature        DECIMAL(3,2)  DEFAULT 0.0,
  max_tokens         INT           DEFAULT 4096,
  timeout_ms         INT           NOT NULL DEFAULT 60000,
  retry_count        INT           NOT NULL DEFAULT 2,
  last_test_status   VARCHAR(30),
  last_tested_at     TIMESTAMP WITH TIME ZONE,
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_ai_configs_public_id UNIQUE (public_id),
  CONSTRAINT uk_ai_configs_project   UNIQUE (project_id),
  CONSTRAINT fk_ai_configs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_ai_configs_project ON ai_configs (project_id);

CREATE TABLE ai_credentials (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  scope             VARCHAR(20)   NOT NULL,
  scope_owner_id    BIGINT,
  provider          VARCHAR(50)   NOT NULL,
  encrypted_api_key TEXT          NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_ai_credentials_public_id UNIQUE (public_id),
  CONSTRAINT chk_ai_credentials_scope_owner CHECK (
    (scope = 'GLOBAL' AND scope_owner_id IS NULL)
    OR
    (scope IN ('PROJECT', 'USER') AND scope_owner_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX uk_ai_credentials_scope_owner_provider
  ON ai_credentials (scope, scope_owner_id, provider) NULLS NOT DISTINCT;
CREATE INDEX idx_ai_credentials_scope ON ai_credentials (scope, scope_owner_id);

CREATE TABLE ai_usage_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      BIGINT        NOT NULL,
  user_id         BIGINT        NOT NULL,
  use_case        VARCHAR(30)   NOT NULL,
  provider        VARCHAR(50)   NOT NULL,
  model           VARCHAR(255)  NOT NULL,
  input_tokens    INT           NOT NULL DEFAULT 0,
  output_tokens   INT           NOT NULL DEFAULT 0,
  total_tokens    INT           NOT NULL DEFAULT 0,
  status          VARCHAR(20)   NOT NULL,
  error_message   TEXT,
  created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

  CONSTRAINT fk_ai_usage_logs_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_ai_usage_logs_user    FOREIGN KEY (user_id)    REFERENCES users (id)
);

CREATE INDEX idx_ai_usage_logs_project_created ON ai_usage_logs (project_id, created_at);
CREATE INDEX idx_ai_usage_logs_user_created    ON ai_usage_logs (user_id, created_at);

-- =============================================================
-- Dataset Schema
-- =============================================================
CREATE TABLE project_schemas (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID   NOT NULL,
  project_id  BIGINT NOT NULL,
  version     INT    NOT NULL DEFAULT 1,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_project_schemas_public_id UNIQUE (public_id),
  CONSTRAINT fk_project_schemas_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_project_schemas_project ON project_schemas (project_id);

CREATE TABLE dataset_columns (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  schema_version_id BIGINT        NOT NULL,
  column_name       VARCHAR(255)  NOT NULL,
  data_type         VARCHAR(30)   NOT NULL,
  role              VARCHAR(30)   NOT NULL,
  sample_value      TEXT,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_dataset_columns_public_id UNIQUE (public_id),
  CONSTRAINT uk_dataset_columns_name UNIQUE (schema_version_id, column_name),
  CONSTRAINT fk_dataset_columns_schema FOREIGN KEY (schema_version_id)
    REFERENCES project_schemas (id) ON DELETE CASCADE
);

CREATE INDEX idx_dataset_columns_schema ON dataset_columns (schema_version_id);

-- =============================================================
-- Datasets
-- =============================================================
CREATE TABLE datasets (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  project_id        BIGINT        NOT NULL,
  name              VARCHAR(255)  NOT NULL,
  description       TEXT,
  source            VARCHAR(30)   NOT NULL,
  schema_version_id BIGINT        NOT NULL,
  latest_version_id BIGINT,
  active_version_id BIGINT,
  total_rows        INT           NOT NULL DEFAULT 0,
  status            VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
  created_by        BIGINT        NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  deleted_at        TIMESTAMP WITH TIME ZONE,

  CONSTRAINT uk_datasets_public_id UNIQUE (public_id),
  CONSTRAINT fk_datasets_project   FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_datasets_schema    FOREIGN KEY (schema_version_id) REFERENCES project_schemas (id),
  CONSTRAINT fk_datasets_creator   FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_datasets_project ON datasets (project_id);

CREATE TABLE dataset_versions (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  dataset_id        BIGINT        NOT NULL,
  schema_version_id BIGINT        NOT NULL,
  version_number    INT           NOT NULL,
  source            VARCHAR(30)   NOT NULL,
  status            VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
  total_rows        INT           NOT NULL DEFAULT 0,
  valid_rows        INT           NOT NULL DEFAULT 0,
  invalid_rows      INT           NOT NULL DEFAULT 0,
  created_by        BIGINT        NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

  CONSTRAINT uk_dataset_versions_public_id UNIQUE (public_id),
  CONSTRAINT uk_dataset_versions_number UNIQUE (dataset_id, version_number),
  CONSTRAINT fk_dataset_versions_dataset FOREIGN KEY (dataset_id) REFERENCES datasets (id),
  CONSTRAINT fk_dataset_versions_schema FOREIGN KEY (schema_version_id) REFERENCES project_schemas (id),
  CONSTRAINT fk_dataset_versions_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_dataset_versions_dataset ON dataset_versions (dataset_id);

ALTER TABLE datasets
  ADD CONSTRAINT fk_datasets_latest_version FOREIGN KEY (latest_version_id) REFERENCES dataset_versions (id),
  ADD CONSTRAINT fk_datasets_active_version FOREIGN KEY (active_version_id) REFERENCES dataset_versions (id);

CREATE TABLE dataset_rows (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id           UUID          NOT NULL,
  dataset_id          BIGINT        NOT NULL,
  dataset_version_id  BIGINT        NOT NULL,
  row_index           INT           NOT NULL,
  data                JSONB         NOT NULL,
  validation_status   VARCHAR(20)   NOT NULL DEFAULT 'VALID',
  validation_errors   JSONB,
  created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

  CONSTRAINT uk_dataset_rows_public_id UNIQUE (public_id),
  CONSTRAINT uk_dataset_rows_version_index UNIQUE (dataset_version_id, row_index),
  CONSTRAINT fk_dataset_rows_dataset FOREIGN KEY (dataset_id) REFERENCES datasets (id) ON DELETE CASCADE,
  CONSTRAINT fk_dataset_rows_version FOREIGN KEY (dataset_version_id)
    REFERENCES dataset_versions (id) ON DELETE CASCADE
);

CREATE INDEX idx_dataset_rows_dataset ON dataset_rows (dataset_id);
CREATE INDEX idx_dataset_rows_version ON dataset_rows (dataset_version_id);

CREATE TABLE dataset_jobs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id          UUID          NOT NULL,
  project_id         BIGINT        NOT NULL,
  dataset_id         BIGINT,
  dataset_version_id BIGINT,
  type               VARCHAR(30)   NOT NULL,
  status             VARCHAR(30)   NOT NULL DEFAULT 'QUEUED',
  progress           INT           NOT NULL DEFAULT 0,
  message            TEXT,
  error_message      TEXT,
  payload            JSONB,
  result             JSONB,
  created_by         BIGINT        NOT NULL,
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  completed_at       TIMESTAMP WITH TIME ZONE,

  CONSTRAINT uk_dataset_jobs_public_id UNIQUE (public_id),
  CONSTRAINT fk_dataset_jobs_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_dataset_jobs_dataset FOREIGN KEY (dataset_id) REFERENCES datasets (id),
  CONSTRAINT fk_dataset_jobs_version FOREIGN KEY (dataset_version_id) REFERENCES dataset_versions (id),
  CONSTRAINT fk_dataset_jobs_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_dataset_jobs_dataset ON dataset_jobs (dataset_id);
CREATE INDEX idx_dataset_jobs_project ON dataset_jobs (project_id);

-- =============================================================
-- Verification Config
-- =============================================================
CREATE TABLE verification_configs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID        NOT NULL,
  project_id  BIGINT      NOT NULL,
  version     INT         NOT NULL DEFAULT 1,
  mode        VARCHAR(30) NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_verification_configs_public_id UNIQUE (public_id),
  CONSTRAINT uk_verification_configs_project   UNIQUE (project_id),
  CONSTRAINT fk_verification_configs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_verification_configs_project ON verification_configs (project_id);

CREATE TABLE verification_items (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                UUID          NOT NULL,
  verification_config_id   BIGINT        NOT NULL,
  type                     VARCHAR(40)   NOT NULL,
  target_paths             JSONB,
  reference_column_keys    JSONB,
  rubric                   TEXT,
  created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_verification_items_public_id UNIQUE (public_id),
  CONSTRAINT fk_verification_items_config FOREIGN KEY (verification_config_id)
    REFERENCES verification_configs (id) ON DELETE CASCADE
);

CREATE INDEX idx_verification_items_config ON verification_items (verification_config_id);

CREATE TABLE verification_field_assertions (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                UUID          NOT NULL,
  verification_item_id     BIGINT        NOT NULL,
  actual_path              VARCHAR(500)  NOT NULL,
  operator                 VARCHAR(50)   NOT NULL,
  expected_column_key      UUID          NOT NULL,
  created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_verification_field_assertions_public_id UNIQUE (public_id),
  CONSTRAINT fk_verification_field_assertions_item FOREIGN KEY (verification_item_id)
    REFERENCES verification_items (id) ON DELETE CASCADE
);

CREATE INDEX idx_verification_field_assertions_item
  ON verification_field_assertions (verification_item_id);
