-- =============================================================
-- Test Runs
-- =============================================================
CREATE TABLE test_runs (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                     UUID          NOT NULL,
  project_id                    BIGINT        NOT NULL,
  name                          VARCHAR(255)  NOT NULL,
  status                        VARCHAR(30)   NOT NULL DEFAULT 'QUEUED',
  target_config_id              BIGINT        NOT NULL,
  target_config_version         INT           NOT NULL,
  ai_config_id                  BIGINT,
  ai_config_version             INT,
  project_schema_id             BIGINT        NOT NULL,
  project_schema_version        INT           NOT NULL,
  dataset_id                    BIGINT        NOT NULL,
  dataset_version_id            BIGINT        NOT NULL,
  dataset_version_number        INT           NOT NULL,
  verification_config_id        BIGINT        NOT NULL,
  verification_config_version   INT           NOT NULL,
  total_cases                   INT           NOT NULL DEFAULT 0,
  passed_cases                  INT           NOT NULL DEFAULT 0,
  failed_cases                  INT           NOT NULL DEFAULT 0,
  error_cases                   INT           NOT NULL DEFAULT 0,
  score                         DECIMAL(7,4)  NOT NULL DEFAULT 0,
  queued_at                     TIMESTAMP WITH TIME ZONE NOT NULL,
  started_at                    TIMESTAMP WITH TIME ZONE,
  finished_at                   TIMESTAMP WITH TIME ZONE,
  duration_ms                   BIGINT,
  cancellation_requested        BOOLEAN       NOT NULL DEFAULT false,
  error_message                 TEXT,
  created_by                    BIGINT        NOT NULL,
  created_at                    TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at                    TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_test_runs_public_id UNIQUE (public_id),
  CONSTRAINT fk_test_runs_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_test_runs_target_config FOREIGN KEY (target_config_id) REFERENCES target_configs (id),
  CONSTRAINT fk_test_runs_ai_config FOREIGN KEY (ai_config_id) REFERENCES ai_configs (id),
  CONSTRAINT fk_test_runs_project_schema FOREIGN KEY (project_schema_id) REFERENCES project_schemas (id),
  CONSTRAINT fk_test_runs_dataset FOREIGN KEY (dataset_id) REFERENCES datasets (id),
  CONSTRAINT fk_test_runs_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES dataset_versions (id),
  CONSTRAINT fk_test_runs_verification_config FOREIGN KEY (verification_config_id) REFERENCES verification_configs (id),
  CONSTRAINT fk_test_runs_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_test_runs_project_created ON test_runs (project_id, created_at DESC);

CREATE TABLE test_results (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id           UUID          NOT NULL,
  run_id              BIGINT        NOT NULL,
  dataset_row_id      BIGINT        NOT NULL,
  case_index          INT           NOT NULL,
  input_data          JSONB         NOT NULL,
  actual_output       JSONB,
  status              VARCHAR(30)   NOT NULL,
  passed              BOOLEAN       NOT NULL,
  score               DECIMAL(7,4)  NOT NULL,
  error_message       TEXT,
  latency_ms          BIGINT,
  raw_target_response JSONB,
  created_at          TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_test_results_public_id UNIQUE (public_id),
  CONSTRAINT fk_test_results_run FOREIGN KEY (run_id) REFERENCES test_runs (id) ON DELETE CASCADE,
  CONSTRAINT fk_test_results_dataset_row FOREIGN KEY (dataset_row_id) REFERENCES dataset_rows (id)
);

CREATE INDEX idx_test_results_run_case ON test_results (run_id, case_index);

CREATE TABLE assertion_results (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id       UUID          NOT NULL,
  test_result_id  BIGINT        NOT NULL,
  assertion_name  VARCHAR(255)  NOT NULL,
  assertion_type  VARCHAR(50)   NOT NULL,
  response_path   VARCHAR(500),
  passed          BOOLEAN       NOT NULL,
  score           DECIMAL(7,4)  NOT NULL,
  reason          TEXT,
  expected_value  TEXT,
  actual_value    TEXT,
  created_at      TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_assertion_results_public_id UNIQUE (public_id),
  CONSTRAINT fk_assertion_results_test_result FOREIGN KEY (test_result_id)
    REFERENCES test_results (id) ON DELETE CASCADE
);

CREATE INDEX idx_assertion_results_test_result ON assertion_results (test_result_id);

CREATE TABLE run_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID          NOT NULL,
  run_id      BIGINT        NOT NULL,
  event_type  VARCHAR(50)   NOT NULL,
  payload     JSONB,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_run_events_public_id UNIQUE (public_id),
  CONSTRAINT fk_run_events_run FOREIGN KEY (run_id) REFERENCES test_runs (id) ON DELETE CASCADE
);

CREATE INDEX idx_run_events_run_created ON run_events (run_id, created_at);
