-- =============================================================
-- Target Config
-- =============================================================
CREATE TABLE target_configs (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                UUID          NOT NULL,
  project_id               BIGINT        NOT NULL,
  version                  INT           NOT NULL DEFAULT 1,
  name                     VARCHAR(255),
  method                   VARCHAR(10)   NOT NULL,
  url                      TEXT          NOT NULL,
  headers                  JSONB,
  query_params             JSONB,
  body_template            TEXT,
  response_path            VARCHAR(500),
  timeout_ms               INT           NOT NULL DEFAULT 30000,
  request_field_snapshot   JSONB,
  response_field_snapshot  JSONB,
  raw_curl                 TEXT,
  last_test_status         VARCHAR(30),
  last_tested_at           TIMESTAMP WITH TIME ZONE,
  created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_target_configs_public_id UNIQUE (public_id),
  CONSTRAINT uk_target_configs_project   UNIQUE (project_id),
  CONSTRAINT fk_target_configs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_target_configs_project ON target_configs (project_id);

-- =============================================================
-- Secret Refs (shared for Target headers + Judge API keys)
-- =============================================================
CREATE TABLE secret_refs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        UUID          NOT NULL,
  project_id       BIGINT        NOT NULL,
  owner_type       VARCHAR(50)   NOT NULL,
  owner_id         BIGINT        NOT NULL,
  secret_name      VARCHAR(255)  NOT NULL,
  secret_location  VARCHAR(50)   NOT NULL,
  secret_path      VARCHAR(500),
  encrypted_value  TEXT          NOT NULL,
  masked_value     VARCHAR(255)  NOT NULL,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_secret_refs_public_id UNIQUE (public_id),
  CONSTRAINT fk_secret_refs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_secret_refs_owner ON secret_refs (owner_type, owner_id);

-- =============================================================
-- Judge Config
-- =============================================================
CREATE TABLE judge_configs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id          UUID          NOT NULL,
  project_id         BIGINT        NOT NULL,
  version            INT           NOT NULL DEFAULT 1,
  provider           VARCHAR(50)   NOT NULL,
  base_url           VARCHAR(500),
  model              VARCHAR(255)  NOT NULL,
  custom_model_name  VARCHAR(255),
  temperature        DECIMAL(3,2)  DEFAULT 0.0,
  max_tokens         INT           DEFAULT 4096,
  timeout_ms         INT           NOT NULL DEFAULT 60000,
  retry_count        INT           NOT NULL DEFAULT 2,
  last_test_status   VARCHAR(30),
  last_tested_at     TIMESTAMP WITH TIME ZONE,
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_judge_configs_public_id UNIQUE (public_id),
  CONSTRAINT uk_judge_configs_project   UNIQUE (project_id),
  CONSTRAINT fk_judge_configs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_judge_configs_project ON judge_configs (project_id);

-- =============================================================
-- Dataset Schema
-- =============================================================
CREATE TABLE dataset_schema_versions (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID   NOT NULL,
  project_id  BIGINT NOT NULL,
  version     INT    NOT NULL DEFAULT 1,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_schema_versions_public_id UNIQUE (public_id),
  CONSTRAINT fk_schema_versions_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_schema_versions_project ON dataset_schema_versions (project_id);

CREATE TABLE dataset_columns (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  schema_version_id BIGINT        NOT NULL,
  column_name       VARCHAR(255)  NOT NULL,
  display_name      VARCHAR(255),
  data_type         VARCHAR(30)   NOT NULL,
  role              VARCHAR(30)   NOT NULL,
  required          BOOLEAN       NOT NULL DEFAULT false,
  sample_value      TEXT,
  description       TEXT,
  display_order     INT           NOT NULL DEFAULT 0,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_dataset_columns_public_id UNIQUE (public_id),
  CONSTRAINT uk_dataset_columns_name UNIQUE (schema_version_id, column_name),
  CONSTRAINT fk_dataset_columns_schema FOREIGN KEY (schema_version_id)
    REFERENCES dataset_schema_versions (id) ON DELETE CASCADE
);

CREATE INDEX idx_dataset_columns_schema ON dataset_columns (schema_version_id);

-- =============================================================
-- Verification Config
-- =============================================================
CREATE TABLE verification_configs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID        NOT NULL,
  project_id  BIGINT      NOT NULL,
  version     INT         NOT NULL DEFAULT 1,
  mode        VARCHAR(30) NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_verification_configs_public_id UNIQUE (public_id),
  CONSTRAINT uk_verification_configs_project   UNIQUE (project_id),
  CONSTRAINT fk_verification_configs_project   FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE INDEX idx_verification_configs_project ON verification_configs (project_id);

CREATE TABLE field_checks (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                UUID          NOT NULL,
  verification_config_id   BIGINT        NOT NULL,
  response_path            VARCHAR(500)  NOT NULL,
  operator                 VARCHAR(50)   NOT NULL,
  expected_source          VARCHAR(30)   NOT NULL,
  expected_column          VARCHAR(255),
  expected_value           TEXT,
  threshold                DECIMAL(5,4),
  weight                   DECIMAL(5,4)  NOT NULL DEFAULT 1.0,
  enabled                  BOOLEAN       NOT NULL DEFAULT true,
  display_order            INT           NOT NULL DEFAULT 0,
  created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_field_checks_public_id UNIQUE (public_id),
  CONSTRAINT fk_field_checks_verification FOREIGN KEY (verification_config_id)
    REFERENCES verification_configs (id) ON DELETE CASCADE
);

CREATE INDEX idx_field_checks_verification ON field_checks (verification_config_id);

CREATE TABLE llm_rubrics (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id                UUID          NOT NULL,
  verification_config_id   BIGINT        NOT NULL,
  name                     VARCHAR(255)  NOT NULL,
  target_path              VARCHAR(500),
  rubric                   TEXT          NOT NULL,
  threshold                DECIMAL(5,4)  DEFAULT 0.7,
  weight                   DECIMAL(5,4)  NOT NULL DEFAULT 1.0,
  enabled                  BOOLEAN       NOT NULL DEFAULT true,
  display_order            INT           NOT NULL DEFAULT 0,
  created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_llm_rubrics_public_id UNIQUE (public_id),
  CONSTRAINT fk_llm_rubrics_verification FOREIGN KEY (verification_config_id)
    REFERENCES verification_configs (id) ON DELETE CASCADE
);

CREATE INDEX idx_llm_rubrics_verification ON llm_rubrics (verification_config_id);
