-- Custom columns defined for a test run
CREATE TABLE test_run_custom_columns (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   UUID          NOT NULL,
  run_id      BIGINT        NOT NULL,
  column_name VARCHAR(255)  NOT NULL,
  data_type   VARCHAR(50)   NOT NULL DEFAULT 'TEXT',
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_test_run_custom_columns_public_id UNIQUE (public_id),
  CONSTRAINT fk_test_run_custom_columns_run FOREIGN KEY (run_id) REFERENCES test_runs (id) ON DELETE CASCADE
);

CREATE INDEX idx_test_run_custom_columns_run ON test_run_custom_columns (run_id);

-- Custom column cell values for each test case result
CREATE TABLE test_result_custom_values (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_result_id    BIGINT        NOT NULL,
  custom_column_id  BIGINT        NOT NULL,
  value             TEXT,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_test_result_custom_values_cell UNIQUE (test_result_id, custom_column_id),
  CONSTRAINT fk_test_result_custom_values_result FOREIGN KEY (test_result_id) REFERENCES test_results (id) ON DELETE CASCADE,
  CONSTRAINT fk_test_result_custom_values_column FOREIGN KEY (custom_column_id) REFERENCES test_run_custom_columns (id) ON DELETE CASCADE
);

CREATE INDEX idx_test_result_custom_values_result ON test_result_custom_values (test_result_id);

-- Overridden status/score by QC
CREATE TABLE test_result_overrides (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  test_result_id    BIGINT        NOT NULL,
  overridden_status VARCHAR(30)   NOT NULL,
  overridden_score  DECIMAL(7,4)  NOT NULL,
  corrected_reason  TEXT,
  corrected_by      BIGINT        NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_test_result_overrides_public_id UNIQUE (public_id),
  CONSTRAINT uk_test_result_overrides_result UNIQUE (test_result_id),
  CONSTRAINT fk_test_result_overrides_result FOREIGN KEY (test_result_id) REFERENCES test_results (id) ON DELETE CASCADE,
  CONSTRAINT fk_test_result_overrides_creator FOREIGN KEY (corrected_by) REFERENCES users (id)
);

-- Async jobs for test runs
CREATE TABLE test_run_jobs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id          UUID          NOT NULL,
  project_id         BIGINT        NOT NULL,
  run_id             BIGINT        NOT NULL,
  type               VARCHAR(30)   NOT NULL,
  status             VARCHAR(30)   NOT NULL DEFAULT 'QUEUED',
  progress           INT           NOT NULL DEFAULT 0,
  message            TEXT,
  error_message      TEXT,
  created_by         BIGINT        NOT NULL,
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
  completed_at       TIMESTAMP WITH TIME ZONE,

  CONSTRAINT uk_test_run_jobs_public_id UNIQUE (public_id),
  CONSTRAINT fk_test_run_jobs_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_test_run_jobs_run FOREIGN KEY (run_id) REFERENCES test_runs (id) ON DELETE CASCADE,
  CONSTRAINT fk_test_run_jobs_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_test_run_jobs_run ON test_run_jobs (run_id);
