-- =============================================================
-- V8: Create ai_credentials table
-- =============================================================

CREATE TABLE ai_credentials (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         UUID          NOT NULL,
  scope             VARCHAR(20)   NOT NULL,
  scope_owner_id    BIGINT,
  provider          VARCHAR(50)   NOT NULL,
  encrypted_api_key TEXT          NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,

  CONSTRAINT uk_ai_credentials_public_id UNIQUE (public_id),

  CONSTRAINT chk_ai_credentials_scope_owner CHECK (
    (scope = 'GLOBAL' AND scope_owner_id IS NULL)
    OR
    (scope IN ('PROJECT', 'USER') AND scope_owner_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX uk_ai_credentials_scope_owner_provider
ON ai_credentials (scope, scope_owner_id, provider) NULLS NOT DISTINCT;

CREATE INDEX idx_ai_credentials_scope ON ai_credentials (scope, scope_owner_id);
