-- =============================================================
-- V9: Create ai_usage_logs table
-- =============================================================

CREATE TABLE ai_usage_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      BIGINT        NOT NULL,
  user_id         BIGINT        NOT NULL,
  use_case        VARCHAR(30)   NOT NULL,
  provider        VARCHAR(50)   NOT NULL,
  model           VARCHAR(255)  NOT NULL,
  input_tokens    INT           NOT NULL DEFAULT 0,
  output_tokens   INT           NOT NULL DEFAULT 0,
  total_tokens    INT           NOT NULL DEFAULT 0,
  status          VARCHAR(20)   NOT NULL,
  error_message   TEXT,
  created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

  CONSTRAINT fk_ai_usage_logs_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_ai_usage_logs_user    FOREIGN KEY (user_id)    REFERENCES users (id)
);

CREATE INDEX idx_ai_usage_logs_project_created ON ai_usage_logs (project_id, created_at);
CREATE INDEX idx_ai_usage_logs_user_created    ON ai_usage_logs (user_id, created_at);
